name: SSH Connect and Add Known Host

on:
  push:
    branches: [main]

jobs:
  ssh_connect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH Connect and Add Known Host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}  # 或者使用 private key
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            # 检查 known_hosts 文件中是否已存在远程主机的公钥指纹
            fingerprint=$(ssh-keygen -H -F "$REMOTE_HOST" | awk '{print $2}')
            if [[ -z "$fingerprint" ]]; then
              echo "远程主机的公钥指纹不存在于 known_hosts 文件中，正在添加..."
              ssh-keyscan -H -p "${{ secrets.REMOTE_PORT }}" "${{ secrets.REMOTE_HOST }}" >> ~/.ssh/known_hosts
              echo "远程主机的公钥指纹已成功添加到 known_hosts 文件中"
            else
              echo "远程主机的公钥指纹已存在于 known_hosts 文件中"
            fi

            # 执行你想要在远程主机上执行的命令
            ssh -p "${{ secrets.REMOTE_PORT }}" "${{ secrets.REMOTE_USERNAME }}@${{ secrets.REMOTE_HOST }}" "echo 'Connection test successful'"
