name: SSH Connect and Add Known Host

on:
  push:
    branches: [main]

jobs:
  ssh_connect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH Connect and Add Known Host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}  # 或者使用 private key
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            ssh root@1.116.133.64 "echo 'Connection test successful'"