name: Go Application CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.0

      - name: Build for CentOS
        run: |
          GOOS=linux GOARCH=amd64 go build -o main

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: go-app
          path: ${{ github.workspace }}/main

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: go-app
          path: ${{ github.workspace }}

      - name: SSH into remote server
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Upload new binary
        run: |
          scp ${{ github.workspace }}/main root@1.116.133.64:~/test/main

      - name: Stop remote process
        run: |
          ssh root@1.116.133.64 "pkill -f main"

      - name: Start new process
        run: |
          ssh root@1.116.133.64 "cd ~/test && nohup ./main &"