name: Go Application CI/CD

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.0

      - name: Build
        run: go build -o myapp

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: go-app
          path: ${{ github.workspace }}

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: go-app


      - name: Add SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 1.116.133.64 >> ~/.ssh/known_hosts

      - name: SSH into remote server
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Check connection status
        run: |
          ssh root@1.116.133.64 "echo 'Connection test successful'"

      - name: Upload project
        run: |
          scp ${{ github.workspace }} root@1.116.133.64:~/test     

      - name: Stop remote process
        run: |
          ssh root@1.116.133.64 "pkill -f myapp"


